### ISSUE TITLE
Add requirements file

### ISSUE THREAD

**Issue by bwheelz36** [jonbmartin/pulpy-tutorials#1]
Reviewing for https://github.com/openjournals/joss-reviews/issues/6586

would be very helpful to add a requirements file. 

The below is at least some of the requirements to run these notebooks

```
pulpy
numba
numpy
PyWavelets
scipy
tqdm
sigpy
matplotlib
jupyter
Ipython
```

**Comment by jonbmartin** [comment]
resolved with Binder setup. Issue with pulpy not installing required packages on install also resolved
